### ISSUE TITLE
Far too many roles.rb's

### ISSUE THREAD

**Issue by ghost** [FormalHellhound/BruhBot-Plugins#3]
I noticed that each command "appends a roles.rb" file. Is that very necessary? I am very sure there is a way to implement a "global" roles function to check, update, delete, and add if needed function. 

``$global[:db] = "Your gems db"
add_query('ALTER TABLE {tableName} ADD COLUMN COLNew {type};')
def add_query(query)
$global[:db].execute(query)
end
``

Let me know if this makes sense..

**Comment by MadnessExpress** [comment]
I have consolidated all of the roles into a single file, along with the database setup files.
